name: Daily AI Task

on:
  schedule:
    - cron: "0 19 * * *"
    - cron: "0 20 * * *"
    - cron: "0 21 * * *"
  push:
    branches:
      - chore/timer

jobs:
  ai_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Skip if AI Task Branch
        if: github.ref == 'refs/heads/chore/timer'
        run: |
          echo "Push from AI task branch detected. Skipping workflow."
          exit 0

      - name: Check Task Enabled
        run: |
          if [ ! -f "task-switch.txt" ]; then
          echo "Control file not found. Exiting."
          exit 0
          fi
          if [ "$(cat task-switch.txt)" == "" ]; then
          echo "Empty task. Exiting."
          exit 0
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Create New Branch
        run: |
          git config --global user.email "limequery@163.com"
          git config --global user.name "0753Lar"
          git checkout chore/timer
          git commit --allow-empty -m "chore: Daily task"

      - name: Run Task
        env:
          HUGGING_FACE_API_KEY: ${{ secrets.HUGGING_FACE_API_KEY }}
        run: |
          for i in $(seq 1 250); do
            echo "Run #$i"
            npm run ai
            git add .
            git commit --amend -m "chore: AI Task Iteration #$i"
            git push origin chore/timer --force
            sleep 3
          done
